"""add the status field in likes table

Revision ID: 3c39c53b3bdf
Revises: b978fc03f2fc
Create Date: 2024-04-30 13:04:52.023702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c39c53b3bdf'
down_revision = 'b978fc03f2fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=10), nullable=False, server_default='active'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
